---
name: bovo
version: 17.08.1
summary: '"Five in a row" board game'
description: 'Bovo is a Gomoku (from Japanese 五目並べ - lit. "five points") like game
    for two players, where the opponents alternate in placing their respective pictogram
    on the game board. (Also known as: Connect Five, Five in a row, X and O, Naughts
    and Crosses)'
confinement: strict
grade: stable
apps:
    bovo:
        command: kf5-launch bovo
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.bovo
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    bovo:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/bovo-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
